{
    "data_version": "4.0",
    "data_type": "CVE",
    "data_format": "MITRE",
    "CVE_data_meta": {
        "ID": "CVE-2022-0718",
        "ASSIGNER": "secalert@redhat.com",
        "STATE": "PUBLIC"
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-522 - Insufficiently Protected Credentials",
                        "cweId": "CWE-522"
                    }
                ]
            }
        ]
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "openstack/python-oslo.utils",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_affected": "=",
                                            "version_value": "Affects all versions, Fixed in 4.10.1, 4.12.1."
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
                "refsource": "MISC",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2056850"
            },
            {
                "url": "https://bugs.launchpad.net/oslo.utils/+bug/1949623",
                "refsource": "MISC",
                "name": "https://bugs.launchpad.net/oslo.utils/+bug/1949623"
            },
            {
                "url": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa",
                "refsource": "MISC",
                "name": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
            },
            {
                "url": "https://security-tracker.debian.org/tracker/CVE-2022-0718",
                "refsource": "MISC",
                "name": "https://security-tracker.debian.org/tracker/CVE-2022-0718"
            },
            {
                "url": "https://access.redhat.com/security/cve/CVE-2022-0718",
                "refsource": "MISC",
                "name": "https://access.redhat.com/security/cve/CVE-2022-0718"
            },
            {
                "url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html",
                "refsource": "MISC",
                "name": "https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html"
            }
        ]
    }
}