{
    "CVE_data_meta": {
        "ASSIGNER": "security-advisories@github.com",
        "ID": "CVE-2021-29471",
        "STATE": "PUBLIC",
        "TITLE": "Denial of service in Matrix Synapse"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "synapse",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "< 1.33.2"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "matrix-org"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "Synapse is a Matrix reference homeserver written in python (pypi package matrix-synapse). Matrix is an ecosystem for open federated Instant Messaging and VoIP. In Synapse before version 1.33.2 \"Push rules\" can specify conditions under which they will match, including `event_match`, which matches event content against a pattern including wildcards. Certain patterns can cause very poor performance in the matching engine, leading to a denial-of-service when processing moderate length events. The issue is patched in version 1.33.2. A potential workaround might be to prevent users from making custom push rules, by blocking such requests at a reverse-proxy."
            }
        ]
    },
    "impact": {
        "cvss": {
            "attackComplexity": "HIGH",
            "attackVector": "NETWORK",
            "availabilityImpact": "LOW",
            "baseScore": 3.7,
            "baseSeverity": "LOW",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "privilegesRequired": "NONE",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "version": "3.1"
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-400: Uncontrolled Resource Consumption"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "https://github.com/matrix-org/synapse/security/advisories/GHSA-x345-32rc-8h85",
                "refsource": "CONFIRM",
                "url": "https://github.com/matrix-org/synapse/security/advisories/GHSA-x345-32rc-8h85"
            },
            {
                "name": "https://github.com/matrix-org/synapse/commit/03318a766cac9f8b053db2214d9c332a977d226c",
                "refsource": "MISC",
                "url": "https://github.com/matrix-org/synapse/commit/03318a766cac9f8b053db2214d9c332a977d226c"
            },
            {
                "name": "https://github.com/matrix-org/synapse/releases/tag/v1.33.2",
                "refsource": "MISC",
                "url": "https://github.com/matrix-org/synapse/releases/tag/v1.33.2"
            }
        ]
    },
    "source": {
        "advisory": "GHSA-x345-32rc-8h85",
        "discovery": "UNKNOWN"
    }
}