{
    "CVE_data_meta": {
        "ASSIGNER": "security-advisories@github.com",
        "ID": "CVE-2022-29205",
        "STATE": "PUBLIC",
        "TITLE": "Segfault due to missing support for quantized types in TensorFlow"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "tensorflow",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "< 2.6.4"
                                        },
                                        {
                                            "version_value": ">= 2.7.0rc0, < 2.7.2"
                                        },
                                        {
                                            "version_value": ">= 2.8.0rc0, < 2.8.1"
                                        },
                                        {
                                            "version_value": ">= 2.9.0rc0, < 2.9.0"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "tensorflow"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "TensorFlow is an open source platform for machine learning. Prior to versions 2.9.0, 2.8.1, 2.7.2, and 2.6.4, there is a potential for segfault / denial of service in TensorFlow by calling `tf.compat.v1.*` ops which don't yet have support for quantized types, which was added after migration to TensorFlow 2.x. In these scenarios, since the kernel is missing, a `nullptr` value is passed to `ParseDimensionValue` for the `py_value` argument. Then, this is dereferenced, resulting in segfault. Versions 2.9.0, 2.8.1, 2.7.2, and 2.6.4 contain a patch for this issue."
            }
        ]
    },
    "impact": {
        "cvss": {
            "attackComplexity": "LOW",
            "attackVector": "LOCAL",
            "availabilityImpact": "HIGH",
            "baseScore": 5.5,
            "baseSeverity": "MEDIUM",
            "confidentialityImpact": "NONE",
            "integrityImpact": "NONE",
            "privilegesRequired": "LOW",
            "scope": "UNCHANGED",
            "userInteraction": "NONE",
            "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "version": "3.1"
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-908: Use of Uninitialized Resource"
                    }
                ]
            },
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-476: NULL Pointer Dereference"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "name": "https://github.com/tensorflow/tensorflow/releases/tag/v2.6.4",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.6.4"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/releases/tag/v2.7.2",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.7.2"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/releases/tag/v2.8.1",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.8.1"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/releases/tag/v2.9.0",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/releases/tag/v2.9.0"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-54ch-gjq5-4976",
                "refsource": "CONFIRM",
                "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-54ch-gjq5-4976"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/commit/237822b59fc504dda2c564787f5d3ad9c4aa62d9",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/commit/237822b59fc504dda2c564787f5d3ad9c4aa62d9"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/blob/f3b9bf4c3c0597563b289c0512e98d4ce81f886e/tensorflow/python/eager/pywrap_tfe_src.cc#L296-L320",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/blob/f3b9bf4c3c0597563b289c0512e98d4ce81f886e/tensorflow/python/eager/pywrap_tfe_src.cc#L296-L320"
            },
            {
                "name": "https://github.com/tensorflow/tensorflow/blob/f3b9bf4c3c0597563b289c0512e98d4ce81f886e/tensorflow/python/eager/pywrap_tfe_src.cc#L480-L482",
                "refsource": "MISC",
                "url": "https://github.com/tensorflow/tensorflow/blob/f3b9bf4c3c0597563b289c0512e98d4ce81f886e/tensorflow/python/eager/pywrap_tfe_src.cc#L480-L482"
            }
        ]
    },
    "source": {
        "advisory": "GHSA-54ch-gjq5-4976",
        "discovery": "UNKNOWN"
    }
}